### ISSUE TITLE
Hope to support Windows

### ISSUE THREAD

**Issue by whit15** [WingCH/image_combine#1]
Thank you very much for opening up this tool, but unfortunately my software only runs on Windows and cannot be used. 
I request the author to provide support for Windows. Thank you again.

**Comment by WingCH** [comment]
Thank you for your feedback! I will try to add Windows support this weekend.

**Comment by WingCH** [comment]
I found that running Windows in a virtual machine on a MacBook for Flutter development is not an easy task.

This project uses the `flutter_rust_bridge` library, which supports Windows.

Ideally, it might only be necessary to add Windows support in pubspec.yaml by including the following configuration:

```yaml
plugin:
  platforms:
    android:
      ffiPlugin: true
    ios:
      ffiPlugin: true
    macos:
      ffiPlugin: true
    windows:
      ffiPlugin: true
```
You can reference this [example](https://github.com/fzyzcjy/flutter_rust_bridge/blob/d5df95cabb57880d94b23abf9f364e0bedc517e9/frb_example/flutter_package/pubspec.yaml#L54)
Please try adding this configuration. If it works, a pull request would be appreciated.
